class UnitDirectionError(ValueError): ...


class InactiveIndexError(IndexError): ...


class NumericalError(RuntimeError): ...


class ZeroMaterializationError(RuntimeError): ...


class SnapshotViolationError(RuntimeError): ...
